#!/usr/bin/env python3
"""Generate the companies/employees test data: shared CSVs + per-dialect schema.

Source: data-sample/japan-test-data/test_data_demo.sqlite (company, employee).
Tables are pluralized and tel/fax/email/birthday values are seeded
deterministically (the original fixture has NULLs there, which would make
masking unobservable).

Outputs:
  docker/test-data/companies.csv, employees.csv   (single data source)
  docker/mysql-init/01-demo.sql                   (DDL + LOAD DATA INFILE from the CSVs)
  docker/pgsql-init/01-demo.sql                   (DDL + COPY from the CSVs)
  script-python/tests/fixtures/schema-sqlite.sql  (DDL only; tests load the CSVs)
"""
import csv
import os
import random
import sqlite3

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
SOURCE = os.path.join(ROOT, "data-sample", "japan-test-data", "test_data_demo.sqlite")
TEST_DATA_DIR = os.path.join(ROOT, "docker", "test-data")

rng = random.Random(20260717)  # fixed seed: regenerating produces identical files

COMPANY_COLUMNS = ["id", "name", "postal_code", "prefecture", "city", "town", "tel", "fax"]
EMPLOYEE_COLUMNS = ["id", "company_id", "name", "name_kana", "birthday",
                    "postal_code", "address", "tel", "fax", "email"]


def fake_tel():
    return f"0{rng.randrange(1, 10)}-{rng.randrange(1000, 10000)}-{rng.randrange(1000, 10000)}"


def fake_birthday():
    year = rng.randrange(1960, 2003)
    month = rng.randrange(1, 13)
    day = rng.randrange(1, 29)
    return f"{year:04d}-{month:02d}-{day:02d}"


def load_source():
    con = sqlite3.connect(SOURCE)
    companies = []
    for row in con.execute(
        "SELECT id, name, postal_code, prefecture, city, town, tel, fax "
        "FROM company ORDER BY id"
    ):
        row = list(row)
        row[6] = row[6] or fake_tel()  # tel
        row[7] = row[7] or fake_tel()  # fax
        companies.append(row)
    employees = []
    for row in con.execute(
        "SELECT id, company_id, name, name_kana, postal_code, address, tel, fax "
        "FROM employee ORDER BY id"
    ):
        (emp_id, company_id, name, name_kana, postal_code, address, tel, fax) = row
        employees.append([
            emp_id, company_id, name, name_kana, fake_birthday(), postal_code,
            address, tel or fake_tel(), fax or fake_tel(),
            f"user{emp_id}@example.org",
        ])
    con.close()
    return companies, employees


DDL = {
    "mysql": """\
SET NAMES utf8mb4;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS companies;
CREATE TABLE companies (
  id INT PRIMARY KEY,
  name VARCHAR(255),
  postal_code VARCHAR(255),
  prefecture VARCHAR(255),
  city VARCHAR(255),
  town VARCHAR(255),
  tel VARCHAR(255),
  fax VARCHAR(255)
) CHARACTER SET utf8mb4;
CREATE TABLE employees (
  id INT PRIMARY KEY,
  company_id INT REFERENCES companies(id),
  name VARCHAR(255),
  name_kana VARCHAR(255),
  birthday DATE,
  postal_code VARCHAR(255),
  address VARCHAR(255),
  tel VARCHAR(255),
  fax VARCHAR(255),
  email VARCHAR(255)
) CHARACTER SET utf8mb4;
""",
    "pgsql": """\
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS companies;
CREATE TABLE companies (
  id INT PRIMARY KEY,
  name VARCHAR(255),
  postal_code VARCHAR(255),
  prefecture VARCHAR(255),
  city VARCHAR(255),
  town VARCHAR(255),
  tel VARCHAR(255),
  fax VARCHAR(255)
);
CREATE TABLE employees (
  id INT PRIMARY KEY,
  company_id INT REFERENCES companies(id),
  name VARCHAR(255),
  name_kana VARCHAR(255),
  birthday DATE,
  postal_code VARCHAR(255),
  address VARCHAR(255),
  tel VARCHAR(255),
  fax VARCHAR(255),
  email VARCHAR(255)
);
""",
    "sqlite": """\
CREATE TABLE companies (
  id INTEGER PRIMARY KEY,
  name TEXT,
  postal_code TEXT,
  prefecture TEXT,
  city TEXT,
  town TEXT,
  tel TEXT,
  fax TEXT
);
CREATE TABLE employees (
  id INTEGER PRIMARY KEY,
  company_id INTEGER REFERENCES companies(id),
  name TEXT,
  name_kana TEXT,
  birthday TEXT,
  postal_code TEXT,
  address TEXT,
  tel TEXT,
  fax TEXT,
  email TEXT
);
""",
}

# The containers mount docker/test-data at /test-data (read-only).
MYSQL_LOAD = """\
LOAD DATA INFILE '/test-data/{table}.csv'
INTO TABLE {table}
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\\n'
IGNORE 1 LINES;
"""

PGSQL_LOAD = """\
COPY {table} FROM '/test-data/{table}.csv' WITH (FORMAT csv, HEADER true);
"""

HEADER_COMMENT = "-- Generated by script-python/tools/generate_test_data.py - do not edit."


def write_csv(path, columns, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, lineterminator="\n")
        writer.writerow(columns)
        writer.writerows(rows)


def write_sql(path, ddl, load_template):
    parts = [HEADER_COMMENT, ddl]
    parts += [load_template.format(table=t) for t in ("companies", "employees")]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))


def main():
    companies, employees = load_source()

    os.makedirs(TEST_DATA_DIR, exist_ok=True)
    write_csv(os.path.join(TEST_DATA_DIR, "companies.csv"), COMPANY_COLUMNS, companies)
    write_csv(os.path.join(TEST_DATA_DIR, "employees.csv"), EMPLOYEE_COLUMNS, employees)

    mysql_out = os.path.join(ROOT, "docker", "mysql-init", "01-demo.sql")
    pgsql_out = os.path.join(ROOT, "docker", "pgsql-init", "01-demo.sql")
    sqlite_out = os.path.join(ROOT, "script-python", "tests", "fixtures", "schema-sqlite.sql")
    for path in (mysql_out, pgsql_out, sqlite_out):
        os.makedirs(os.path.dirname(path), exist_ok=True)
    write_sql(mysql_out, DDL["mysql"], MYSQL_LOAD)
    write_sql(pgsql_out, DDL["pgsql"], PGSQL_LOAD)
    with open(sqlite_out, "w", encoding="utf-8") as f:
        f.write(HEADER_COMMENT + "\n" + DDL["sqlite"])

    print(f"{TEST_DATA_DIR}: {len(companies)} companies, {len(employees)} employees")
    for path in (mysql_out, pgsql_out, sqlite_out):
        print(path)


if __name__ == "__main__":
    main()
