-- Generated by script-python/tools/generate_test_data.py - do not edit.
SET NAMES utf8mb4;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS companies;
CREATE TABLE companies (
  id INT PRIMARY KEY,
  name VARCHAR(255),
  postal_code VARCHAR(255),
  prefecture VARCHAR(255),
  city VARCHAR(255),
  town VARCHAR(255),
  tel VARCHAR(255),
  fax VARCHAR(255)
) CHARACTER SET utf8mb4;
CREATE TABLE employees (
  id INT PRIMARY KEY,
  company_id INT REFERENCES companies(id),
  name VARCHAR(255),
  name_kana VARCHAR(255),
  birthday DATE,
  postal_code VARCHAR(255),
  address VARCHAR(255),
  tel VARCHAR(255),
  fax VARCHAR(255),
  email VARCHAR(255)
) CHARACTER SET utf8mb4;

LOAD DATA INFILE '/test-data/companies.csv'
INTO TABLE companies
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE '/test-data/employees.csv'
INTO TABLE employees
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
