-- Generated by script-python/tools/generate_test_data.py - do not edit.
CREATE TABLE companies (
  id INTEGER PRIMARY KEY,
  name TEXT,
  postal_code TEXT,
  prefecture TEXT,
  city TEXT,
  town TEXT,
  tel TEXT,
  fax TEXT
);
CREATE TABLE employees (
  id INTEGER PRIMARY KEY,
  company_id INTEGER REFERENCES companies(id),
  name TEXT,
  name_kana TEXT,
  birthday TEXT,
  postal_code TEXT,
  address TEXT,
  tel TEXT,
  fax TEXT,
  email TEXT
);
